name: my_tasks
description: "a simple little app for posting and completing tasks"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.6

  # state management
  flutter_bloc: any

  # objects equals
  equatable: any

  # data base
  shared_preferences: ^2.0.5

  # dependency injection
  get_it: any

  # ui component
  flutter_slidable: any
  animations: any
  scrollable_positioned_list: any
  lottie: any
  intl: ^0.17.0
  feature_discovery: any
  flutter_staggered_animations: any
  flutter_local_notifications: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "lib/icons/app_icon.png"
  adaptive_icon_foreground: "lib/icons/adaptive_icon_foreground.png"
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/monda/
    - assets/fonts/poppins/
    - assets/fonts/ubuntu/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - lib/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: Monda
      fonts:
        - asset: assets/fonts/monda/Monda-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf